### ISSUE TITLE
After Python 3.10 Upgrade...

### ISSUE THREAD

**Issue by MatheuwHiggen** [dhylands/rshell#167]
After upgrading my system (Windows) to Python 3.10 I got following error:

Traceback (most recent call last):
  File "C:\Program Files\Python310\Scripts\rshell-script.py", line 33, in <module>
    sys.exit(load_entry_point('rshell==0.0.30', 'console_scripts', 'rshell')())
  File "C:\Program Files\Python310\Scripts\rshell-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Program Files\Python310\lib\importlib\metadata\__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files\Python310\lib\site-packages\rshell\command_line.py", line 1, in <module>
    import rshell.main
  File "C:\Program Files\Python310\lib\site-packages\rshell\main.py", line 80, in <module>
    import readline
  File "C:\Program Files\Python310\lib\site-packages\readline.py", line 34, in <module>
    rl = Readline()
  File "C:\Program Files\Python310\lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "C:\Program Files\Python310\lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "C:\Program Files\Python310\lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "C:\Program Files\Python310\lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
  File "C:\Program Files\Python310\lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'

Any ideas?!

**Comment by davehylands** [comment]
I upgraded one of my linux machines to ubuntu 21.10 and install Python 3.10 be following these instructions: https://www.debugpoint.com/2021/10/install-python-3-10-ubuntu/

Once I had python3.10 as the default, then rshell worked fine for me with my pyboard (although the prompt wasn't showing in color).

I installed rshell by using the command:
```
python3 -m pip install rshell
```

**Comment by moefear85** [comment]
this seems like a windows+python3.10 issue. I'm facing it too right now. Guess I'll have to reboot to linux

**Comment by iandouglas** [comment]
On Windows, rshell wants to install pyreadline, not regular readline

**Comment by timg11** [comment]
@iandouglas  that is the exact issue I'm having. I just installed rshell with "pip install rshell" it installed pyreadline, and I get the error "AttributeError: module 'collections' has no attribute 'Callable'".
DId you find a workaround? Is there a different installation procedure that installs readline?
