### ISSUE TITLE
rshell - python 3.10 - Ubuntu 22.10 - AttributeError: module 'serial' has no attribute 'VERSION'

### ISSUE THREAD

**Issue by krishnak** [dhylands/rshell#220]
I am returning back to micropython development after almost a year, the same laptop which used to connect to ESP32 micropython board using rshell is no longer working. However I am able to connect to the board using picccom.

The issue appears to be some python related, can you throw some light

```
krishnak@tapati:~/esp32/micropython$ rshell --port /dev/ttyUSB0 
Using buffer-size of 32
Connecting to /dev/ttyUSB0 (buffer-size 32)...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rshell/main.py", line 1381, in connect
    ip_address = socket.gethostbyname(port)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/rshell", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/rshell/command_line.py", line 4, in main
    rshell.main.main()
  File "/usr/local/lib/python3.10/dist-packages/rshell/main.py", line 3082, in main
    real_main()
  File "/usr/local/lib/python3.10/dist-packages/rshell/main.py", line 3044, in real_main
    connect(args.port, baud=args.baud, wait=args.wait, user=args.user, password=args.password)
  File "/usr/local/lib/python3.10/dist-packages/rshell/main.py", line 1387, in connect
    connect_serial(port, baud=baud, wait=wait)
  File "/usr/local/lib/python3.10/dist-packages/rshell/main.py", line 1411, in connect_serial
    dev = DeviceSerial(port, baud, wait)
  File "/usr/local/lib/python3.10/dist-packages/rshell/main.py", line 1694, in __init__
    pyb = Pyboard(port, baudrate=baud, wait=wait, rts=RTS, dtr=DTR)
  File "/usr/local/lib/python3.10/dist-packages/rshell/pyboard.py", line 130, in __init__
    if serial.VERSION == '3.0':
AttributeError: module 'serial' has no attribute 'VERSION'

```

**Comment by krishnak** [comment]
sudo pip3 install --ignore-installed -U pyserial

Run the above command to force install, when I install with out --ignore-installed - it doesn't install the newer version for some reason

**Comment by krishnak** [comment]
sudo pip3 install --ignore-installed -U pyserial

To Resolve execute the above command to force install, when I install with out --ignore-installed - it doesn't install the newer version for some reason
