### ISSUE TITLE
Cannot install `rshell`

### ISSUE THREAD

**Issue by cwharris** [dhylands/rshell#237]
It appears `setup.py` is attempting to import `rshell` during installation, which fails (at least in my conda environment on ubuntu 22.04) presumably due to `rshell` being treated as an installed module name and not a relative path.

```
(esp32) coder ➜ ~/dev $ pip install rshell
Collecting rshell
  Using cached rshell-0.0.34.tar.gz (48 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-xdjoq0y6/rshell_668fb8047ccf456cb27890b00925f999/setup.py", line 9, in <module>
          from rshell.version import __version__
      ModuleNotFoundError: No module named 'rshell'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by dhylands** [comment]
I fixed this in 0.0.35 so that setup.py now uses a different method to determine the version.
