### ISSUE TITLE
rshell won't connect to micropython on esp8266

### ISSUE THREAD

**Issue by larsks** [dhylands/rshell#37]
I'm running `MicroPython v1.9.3 on 2017-11-16; ESP module with ESP8266`.  If I try to connect with `rshell` using the `connect serial` command I get the following exception:

```
$ rshell
Welcome to rshell. Use Control-D to exit.

No MicroPython boards connected - use the connect command to add one

/home/lars/projects/tempmonitor> connect serial /dev/ttyUSB1
Connecting to /dev/ttyUSB1 ...
Traceback (most recent call last):
  File "/home/lars/projects/tempmonitor/.venv/bin/rshell", line 11, in <module>
    sys.exit(main())
  File "/home/lars/projects/tempmonitor/.venv/lib/python3.5/site-packages/rshell/command_line.py", line 4, in main
    rshell.main.main()
  File "/home/lars/projects/tempmonitor/.venv/lib/python3.5/site-packages/rshell/main.py", line 2658, in main
    real_main()
  File "/home/lars/projects/tempmonitor/.venv/lib/python3.5/site-packages/rshell/main.py", line 2641, in real_main
    shell.cmdloop(cmd_line)
  File "/home/lars/projects/tempmonitor/.venv/lib/python3.5/site-packages/rshell/main.py", line 1551, in cmdloop
    cmd.Cmd.cmdloop(self)
  File "/usr/lib64/python3.5/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/home/lars/projects/tempmonitor/.venv/lib/python3.5/site-packages/rshell/main.py", line 1581, in onecmd
    self.onecmd_exec("".join(group))
  File "/home/lars/projects/tempmonitor/.venv/lib/python3.5/site-packages/rshell/main.py", line 1592, in onecmd_exec
    return cmd.Cmd.onecmd(self, line)
  File "/usr/lib64/python3.5/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/lars/projects/tempmonitor/.venv/lib/python3.5/site-packages/rshell/main.py", line 1905, in do_connect
    connect_serial(port, baud)
  File "/home/lars/projects/tempmonitor/.venv/lib/python3.5/site-packages/rshell/main.py", line 1215, in connect_serial
    dev = DeviceSerial(port, baud, wait)
  File "/home/lars/projects/tempmonitor/.venv/lib/python3.5/site-packages/rshell/main.py", line 1436, in __init__
    Device.__init__(self, pyb)
  File "/home/lars/projects/tempmonitor/.venv/lib/python3.5/site-packages/rshell/main.py", line 1273, in __init__
    self.name = self.remote_eval(board_name, self.default_board_name())
  File "/home/lars/projects/tempmonitor/.venv/lib/python3.5/site-packages/rshell/main.py", line 1353, in remote_eval
    return eval(self.remote(func, *args, **kwargs))
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

```

**Comment by larsks** [comment]
Ah, I've solved this one.  It's because I had a file named `board.py`, which apparently conflicts with something that `rshell` was expecting?  There is no `board` module in the esp8266 port, at least.  I guess I will need to find another name.

**Comment by dhylands** [comment]
Ah yes - rshell supports connecting to multiple boards and it does this by looking for a boards.py file.

**Comment by cefn** [comment]
Is there a workaround which doesn't involve renaming board.py?

I have an impossible situation since there has to be a module named exactly board.py for compatibility with Circuitpython...
https://github.com/adafruit/Adafruit_Micropython_Blinka/tree/master/src

I ran into this when trying to rsync packages to a Micropython board with the Blinka compatibility layer installed and don't know what options I have, (aside from scripting ampy to remove and replace the file after every rsync).

**Comment by cefn** [comment]
As a workaround I just made sure there was in fact a string name value within Blinka board.py. What principled way is there to populate this? Currently it's populated according to the board type, but that will mean a clash when using rshell with e.g. more than one Feather Huzzah. Is there a minimal identifier already available in memory somewhere (e.g. a unique identifier which doesn't require loading e.g. a network library to get a mac address).

**Comment by dhylands** [comment]
You could edit main.py in rshell here:
https://github.com/dhylands/rshell/blob/b148481f2f4fd4c567a151ac4a905e118a0b9857/rshell/main.py#L527-L534
Change 'import board' and 'board.name' to something else.

I'll need to figure out an alternative to work with CircuitPython
