### ISSUE TITLE
Error on rshell installation

### ISSUE THREAD

**Issue by bobbyEH2018** [dhylands/rshell#50]
Hello, I'm using raspberry pi 3 model B and ESP32 board made by WEMOS. (URL is shown on bottom)

And I'm reading this page ( ↓URL) to play with raspberry pi and ESP32. 
https://www.rototron.info/raspberry-pi-esp32-micropython-tutorial/
And now I got problem to install and activate rshell as shown below.
I'm glad if you could have some advice or hint to solve this problem.

I have a copy of all commands and scripts shown on the shell.
[pi_all.docx](https://github.com/dhylands/rshell/files/2086755/pi_all.docx)

Anyway, thank you for reading my question.

**pi@raspberrypi:~ $ sudo pip3 install rshell**
```
Downloading/unpacking rshell
  Downloading rshell-0.0.13.tar.gz (41kB): 41kB downloaded
  Running setup.py (path:/tmp/pip-build-7ejbpxl9/rshell/setup.py) egg_info for package rshell
    
    package init file 'tests/__init__.py' not found (or not a regular file)
    warning: no files found matching 'tests/test-rshell.shr'
Requirement already satisfied (use --upgrade to upgrade): pyserial in /usr/lib/python3/dist-packages (from rshell)
Downloading/unpacking pyudev>=0.16 (from rshell)
  Downloading pyudev-0.21.0.tar.gz (89kB): 89kB downloaded
  Running setup.py (path:/tmp/pip-build-7ejbpxl9/pyudev/setup.py) egg_info for package pyudev
    
    warning: no previously-included files matching '*.py' found under directory 'tests/.hypothesis'
    warning: no files found matching '*.c' under directory 'reproducers'
    warning: no files found matching '*.py' under directory 'reproducers'
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python3/dist-packages (from pyudev>=0.16->rshell)
Installing collected packages: rshell, pyudev
  Running setup.py install for rshell
    package init file 'tests/__init__.py' not found (or not a regular file)
      File "/usr/local/lib/python3.4/dist-packages/rshell/main.py", line 508
        wrapper.extra_funcs = [*funcs]
                                  ^
    SyntaxError: can use starred expression only as assignment target
    
    
    warning: no files found matching 'tests/test-rshell.shr'
    Installing pyboard script to /usr/local/bin
    Installing rshell script to /usr/local/bin
  Running setup.py install for pyudev
    
    warning: no previously-included files matching '*.py' found under directory 'tests/.hypothesis'
    warning: no files found matching '*.c' under directory 'reproducers'
    warning: no files found matching '*.py' under directory 'reproducers'
Successfully installed rshell pyudev
Cleaning up...
```

**pi@raspberrypi:~ $ rshell --buffer-size=30 -p /dev/ttyUSB0**
```
Traceback (most recent call last):
  File "/usr/local/bin/rshell", line 9, in <module>
    load_entry_point('rshell==0.0.13', 'console_scripts', 'rshell')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/rshell/command_line.py", line 1, in <module>
    import rshell.main
  File "/usr/local/lib/python3.4/dist-packages/rshell/main.py", line 508
    wrapper.extra_funcs = [*funcs]
                              ^
SyntaxError: can use starred expression only as assignment target

```
●ESP32 WEMOS board
https://www.mosfex.com/product/86/%E0%B8%9A%E0%B8%AD%E0%B8%A3%E0%B9%8C%E0%B8%94%E0%B8%9E%E0%B8%B1%E0%B8%92%E0%B8%99%E0%B8%B2-iot-wemos%C2%AE-lolin32-v1-0-0-esp32-wifibluetooth-%E0%B8%95%E0%B9%88%E0%B8%AD%E0%B9%81%E0%B8%9A%E0%B8%95-lipo-li-ion-%E0%B9%84%E0%B8%94%E0%B9%89-%E0%B8%8A%E0%B8%B2%E0%B8%A3%E0%B9%8C%E0%B8%88%E0%B9%84%E0%B8%94%E0%B9%89

**Comment by bobbyEH2018** [comment]
[pi_all.docx](https://github.com/dhylands/rshell/files/2086755/pi_all.docx)

**Comment by bobbyEH2018** [comment]
I did reinstall rasbian OS and retry. it works.
