### ISSUE TITLE
board.py and syntax errors

### ISSUE THREAD

**Issue by rhubarbdog** [dhylands/rshell#87]
I read the instructions for rshell downloaded it and gave it a try.
I thought i'd try `board.py` board naming.
when my `board.py` erroneously read
```
RED_PYB
```
and erroneously read
```
name = RED_PYB
```
I get the following unhelpful output trace
```
Connecting to /dev/ttyACM0 (buffer-size 512)...
Trying to connect to REPL  connected
Testing if sys.stdin.buffer exists ... Y
Retrieving root directories ... /flash/
Setting time ... Apr 18, 2019 23:28:42
Evaluating board_name ... Traceback (most recent call last):
  File "/usr/local/bin/rshell", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/rshell/command_line.py", line 4, in main
    rshell.main.main()
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 2843, in main
    real_main()
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 2809, in real_main
    autoscan()
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 315, in autoscan
    connect_serial(port[0])
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 1285, in connect_serial
    dev = DeviceSerial(port, baud, wait)
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 1565, in __init__
    Device.__init__(self, pyb)
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 1350, in __init__
    self.name = self.remote_eval_last(board_name, self.default_board_name())
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 1465, in remote_eval_last
    return eval(self.remote(func, *args, **kwargs).split()[-1])
IndexError: list index out of range
```

**Comment by dhylands** [comment]
This should be fixed by b717e3c0cd6dc05d0c80e627e4e1f88fcde1c43b
