### ISSUE TITLE
`ls` crashes when there are broken links in directory

### ISSUE THREAD

**Issue by rhubarbdog** [dhylands/rshell#88]
from a prompt i enter command `rshell`
I enter the command `ls` and get the following traceback
```
Traceback (most recent call last):
  File "/usr/local/bin/rshell", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/rshell/command_line.py", line 4, in main
    rshell.main.main()
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 2843, in main
    real_main()
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 2826, in real_main
    shell.cmdloop(cmd_line)
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 1692, in cmdloop
    cmd.Cmd.cmdloop(self)
  File "/usr/lib/python3.5/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 1722, in onecmd
    self.onecmd_exec("".join(group))
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 1733, in onecmd_exec
    return cmd.Cmd.onecmd(self, line)
  File "/usr/lib/python3.5/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 2319, in do_ls
    ldir_stat = auto(listdir_stat, filename)
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 585, in auto
    return func(dev_filename, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 569, in wrapper
    return real_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 771, in listdir_stat
    return list((file, stat(dirname + '/' + file)) for file in files if is_visible(file) or show_hidden)
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 771, in <genexpr>
    return list((file, stat(dirname + '/' + file)) for file in files if is_visible(file) or show_hidden)
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 703, in stat
    rstat = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/phil/projects/pyboard/pyb_sd'
```

the file `/home/phil/projects/pyboard/pyb_sd` exists but is a broken softlink it points to my SD Card when in the reader on my laptop

**Comment by dhylands** [comment]
This should be fixed by 97a067143d4064e6ef3314813415d713b3d7f649
