### ISSUE TITLE
problems with broken links and equally matching tab completions

### ISSUE THREAD

**Issue by rhubarbdog** [dhylands/rshell#92]
i'm trying to edit the fie `pybwfi.py` which exists in a directory with broken soft link `pyb_sd`
I get the following output after typing `edit pyb` then pressing tab
```
> edit pybTraceback (most recent call last):
  File "/home/phil/git/rshell/rshell/main.py", line 1841, in filename_complete
    return self.real_filename_complete(text, line, begidx, endidx)
  File "/home/phil/git/rshell/rshell/main.py", line 1910, in real_filename_complete
    paths = sorted(auto(listdir_matches, match))
  File "/home/phil/git/rshell/rshell/main.py", line 585, in auto
    return func(dev_filename, *args, **kwargs)
  File "/home/phil/git/rshell/rshell/main.py", line 768, in listdir_matches
    for filename in os.listdir(dirname) if filename.startswith(match_prefix)]
  File "/home/phil/git/rshell/rshell/main.py", line 768, in <listcomp>
    for filename in os.listdir(dirname) if filename.startswith(match_prefix)]
  File "/home/phil/git/rshell/rshell/main.py", line 764, in add_suffix_if_dir
    if (os.stat(filename)[0] & 0x4000) != 0:
FileNotFoundError: [Errno 2] No such file or directory: 'pyb_sd'
```
I'm using an uptodate commit which includes commit https://github.com/dhylands/rshell/commit/97a067143d4064e6ef3314813415d713b3d7f649

**Comment by dhylands** [comment]
This should have been fixed by 62f2f606ebc9263b23b080c48485027814f90fa8 which added:
https://github.com/dhylands/rshell/commit/62f2f606ebc9263b23b080c48485027814f90fa8#diff-83be38289f7553c9acd1db80690a2aacR764
