### ISSUE TITLE
Erroneous lone escape character '\' leads to a crash

### ISSUE THREAD

**Issue by rhubarbdog** [dhylands/rshell#98]
when using rshell i typed `ls /sd` when i pressed enter i accidentally also pressed `\` resulting in command `ls /sd\` this produced the following output traceback.
```
Traceback (most recent call last):
  File "/usr/local/bin/rshell", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/rshell/command_line.py", line 4, in main
    rshell.main.main()
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 2843, in main
    real_main()
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 2826, in real_main
    shell.cmdloop(cmd_line)
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 1692, in cmdloop
    cmd.Cmd.cmdloop(self)
  File "/usr/lib/python3.5/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 1722, in onecmd
    self.onecmd_exec("".join(group))
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 1733, in onecmd_exec
    return cmd.Cmd.onecmd(self, line)
  File "/usr/lib/python3.5/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 2291, in do_ls
    args = self.line_to_args(line)
  File "/usr/local/lib/python3.5/dist-packages/rshell/main.py", line 1897, in line_to_args
    args = shlex.split(line)
  File "/usr/lib/python3.5/shlex.py", line 273, in split
    return list(lex)
  File "/usr/lib/python3.5/shlex.py", line 263, in __next__
    token = self.get_token()
  File "/usr/lib/python3.5/shlex.py", line 90, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.5/shlex.py", line 185, in read_token
    raise ValueError("No escaped character")
ValueError: No escaped character
```

**Comment by dhylands** [comment]
I just released 0.0.25 which includes this fix
